### ISSUE TITLE
Support for Google Ecommerce Tracking

### ISSUE THREAD

**Issue by khalibloo** [khalibloo/saleor-alt-storefront#84]
Add support for Google Ecommerce (GA4) through Google Tag Manager.
- [x] product list views
- [x] product clicks
- [x] product detail views
- [x] add to cart
- [x] remove from cart
- [x] promo view
- [x] promo click
- [x] begin checkout
- [x] purchase
- [x] add shipping method
- [x] login
- [x] signup
- [x] search
